spring:
  application:
    name: notification-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://localhost:5000,optional:configserver:http://localhost:5001
  cloud:
    config:
      label: main
