spring:
  application:
    name: payments-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://localhost:5000,optional:configserver:http://localhost:5001
  cloud:
    config:
      label: main
      #fail-fast: on
      #request-connect-timeout: 10
      #request-read-timeout: 10
